<?php

namespace Proxies\__CG__\A2F\SofiaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DATABASE extends \A2F\SofiaBundle\Entity\DATABASE implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'A2F\\SofiaBundle\\Entity\\DATABASE' . "\0" . 'dbms', '' . "\0" . 'A2F\\SofiaBundle\\Entity\\DATABASE' . "\0" . 'server', 'id', 'name', 'size', 'notes', 'live', 'criticality', 'client');
        }

        return array('__isInitialized__', '' . "\0" . 'A2F\\SofiaBundle\\Entity\\DATABASE' . "\0" . 'dbms', '' . "\0" . 'A2F\\SofiaBundle\\Entity\\DATABASE' . "\0" . 'server', 'id', 'name', 'size', 'notes', 'live', 'criticality', 'client');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DATABASE $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUniqueName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueName', array());

        return parent::getUniqueName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbms(\A2F\SofiaBundle\Entity\DBMS $dbms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbms', array($dbms));

        return parent::setDbms($dbms);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbms', array());

        return parent::getDbms();
    }

    /**
     * {@inheritDoc}
     */
    public function setServer(\A2F\SofiaBundle\Entity\SERVER $server)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServer', array($server));

        return parent::setServer($server);
    }

    /**
     * {@inheritDoc}
     */
    public function getServer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServer', array());

        return parent::getServer();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', array($size));

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', array());

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setLive($live)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLive', array($live));

        return parent::setLive($live);
    }

    /**
     * {@inheritDoc}
     */
    public function getLive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLive', array());

        return parent::getLive();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriticality(\A2F\SofiaBundle\Entity\CRITICALITY $criticality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriticality', array($criticality));

        return parent::setCriticality($criticality);
    }

    /**
     * {@inheritDoc}
     */
    public function getCriticality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriticality', array());

        return parent::getCriticality();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\A2F\SofiaBundle\Entity\CLIENT $client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

}
