<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CLIENTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CLIENTRepository extends EntityRepository
{
    public function findOneClientById($id)
    {
        return $this->createQueryBuilder("c")
                    ->where("c.id =:id")
                    ->setParameter("id", $id)
                    ->getQuery()
                    ->getOneOrNullResult()
                ;   
    }
    
     public function findAllClients()
        {
            return $this->createQueryBuilder("c")
                        ->addOrderBy("c.companyName", "DESC")
                        ->getQuery()
                        ->getResult();
}
}