<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CONTRACTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CONTRACTRepository extends EntityRepository
    {
        public function findAllContracts($limit = null)
            {
                                
                return $this->createQueryBuilder("c")
                            ->addSelect("ct")
                            ->addSelect("gti")
                            ->addSelect("clt")
                            ->leftJoin("c.contractType", "ct")
                            ->leftJoin("c.gti", "gti")
                            ->leftJoin("c.client", "clt")
                            ->where("c.endDate > :today")
                            ->orderBy("gti", "ASC")
                            ->orderBy("c.startDate", "ASC")
                            ->setParameter("today", new \DateTime("now"))
                            ->setMaxResults($limit)
                            ->getQuery()
                            ->getResult();
                            
                        
            }
            
            public function findAllLiveContractsByClient($id)
            {
                return $this->createQueryBuilder("c")
                            ->addSelect("ct")
                            ->addSelect("clt")
                            ->leftJoin("c.contractType", "ct")
                            ->leftJoin("c.client", "clt")
                           // ->where("c.endDate > :new \DateTime()")
                            ->where("clt.id =:id")
                            ->orderBy("c.startDate", "ASC")
                            ->setParameter("id", $id)
                            ->getQuery()
                            ->getResult();
            }
            
            public function findAllContractsByClient($id)
            {
                return $this->createQueryBuilder("c")
                        ->addSelect("clt")
                        ->leftJoin("c.client", "clt")
                        ->where("clt.id = :id")
                        ->orderBy("c.startDate", "ASC")
                        ->setParameter("id", $id)
                        ->getQuery()
                        ->getResult();
            }
        
    }
