<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DATABASERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DATABASERepository extends EntityRepository
{
    public function getAllDataBasesByClient($id)
    {
        return $this->createQueryBuilder("db")
                        ->addSelect("clt")
                        ->addSelect("ser")
                        ->addSelect("crit")
                        ->leftJoin("db.client", "clt")
                        ->leftJoin("db.criticality", "crit")
                        ->leftJoin("db.server", "ser")
                        ->where("clt.id = :id")
                        ->addOrderBy("db.live", "DESC")
                        ->setParameter("id", $id);
                        
    }


    public function findAllDataBasesByClient($limit, $id)
        {
            return $this->createQueryBuilder("db")
                        ->addSelect("clt")
                        ->addSelect("crit")
                        ->leftJoin("db.client", "clt")
                        ->leftJoin("db.criticality", "crit")
                        ->where("clt.id = :id")
                        ->addOrderBy("db.live", "DESC")
                        ->setParameter("id", $id)
                        ->setMaxResults($limit)
                        ->getQuery()
                        ->getResult();
        }
}
