<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DBARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DBARepository extends EntityRepository
{
    public function FindOneUserById($id)
        {
            return $this->createQueryBuilder("dba")
                        ->where("dba.id =:id")
                        ->setParameter("id", $id)
                        ->getQuery()
                        ->getOneOrNullResult();
        }
}
