<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NOTIFICATIONRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NOTIFICATIONRepository extends EntityRepository
{
     public function findAllNotificationsByClient($limit, $id)
        {
            return $this->createQueryBuilder("n")
                        ->addSelect("clt")
                        ->leftJoin("n.client", "clt")
                        ->where("clt.id = :id")
                        ->addOrderBy("n.creationDate", "DESC")
                        ->setParameter("id", $id)
                        ->setMaxResults($limit)
                        ->getQuery()
                        ->getResult();
        }
}
