<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * REQUESTERRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class REQUESTERRepository extends EntityRepository
{
    
    public function findAllRequestersByClient($id)
        {
            
            return $this->createQueryBuilder("r")
                        ->addSelect("c")
                        ->leftJoin("r.client", "c")
                        ->where("c.id = :id")
                        ->addOrderBy("r.live", "DESC")
                        ->setParameter("id", $id)
                        ->getQuery()
                        ->getResult();
        }
        
    public function findOneUserById($id)
    {
        return $this->createQueryBuilder("u")
                    ->where("u.id =:id")
                    ->setParameter("id", $id)
                    ->getQuery()
                    ->getOneOrNullResult()
                ;   
    }
}
