<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SERVERRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SERVERRepository extends EntityRepository
{
    
    public function findAllServersByClient($limit, $id)
        {
            return $this->createQueryBuilder("ser")
                        ->addSelect("clt")
                        ->addSelect("crit")
                        ->addSelect("db")
                        ->leftJoin("ser.client", "clt")
                        ->leftJoin("ser.criticality", "crit")
                        ->leftJoin("ser.dbs", "db")
                        ->where("clt.id = :id")
                        ->addOrderBy("ser.live", "DESC")
                        ->setParameter("id", $id)
                        ->setMaxResults($limit)
                        ->getQuery()
                        ->getResult();
        }
}
