<?php

namespace A2F\SofiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SERVERTYPERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SERVERTYPERepository extends EntityRepository
{
}
